version: 2
jobs:
  build:
    docker:
      - image: golang
    working_directory: /go/src/github.com/vmware/go-nfs-client

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - run: go get -t -v ./...

      - run: go get github.com/jstemmer/go-junit-report
      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make testv | tee ${TEST_RESULTS}/go-test.out

      - run:
          name: Run code coverage
          command: |
            make coverage
            cp cover.html /tmp/test-results
            bash <(curl -s https://codecov.io/bash) -c -F unittests

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
